name: Deploy on serveur

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      server_name:
        required: true
        type: string

    secrets:      
      dockerhub_token:
        required: true
      dockerhub_username:
        required: true
      server:
        required: true
      serveur_user:
        required: true
      serveur_pwd:
        required: true
      serveur_port:
        required: true

jobs:

  prod:
    name: Deployment on '${{ inputs.server_name }}' server
    runs-on: ubuntu-latest
    steps:

      - name: SSH on ${{ inputs.server_name }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.server }}
          username: ${{ secrets.serveur_user }}
          password: ${{ secrets.serveur_pwd }}
          port: ${{ secrets.serveur_port }}
          script: |
            echo Login
            echo ${{ secrets.dockerhub_token }} | docker login -u ${{ secrets.dockerhub_username }} --password-stdin

            echo List docker images on server
            docker ps -a

            echo Delete image
            docker rm -f $(docker ps -a | grep squaddev | awk '{print $1}')

            echo Pull image
            docker pull ${{ secrets.dockerhub_username }}/${{ secrets.dockerhub_username }}:${{ inputs.image_tag }}

            echo Run new one
            docker run -d -p 3000:80 --name squaddev ${{ secrets.dockerhub_username }}/squaddev:${{ inputs.image_tag }}